# Generated by Django 4.1 on 2023-07-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='memberdets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('MemberName', models.CharField(default='', max_length=200, null=True)),
                ('Contactnumber', models.CharField(default='', max_length=200, null=True)),
                ('Email', models.CharField(default='', max_length=200, null=True)),
                ('DateofBirth', models.CharField(default='', max_length=200, null=True)),
                ('Gender', models.CharField(default='', max_length=200, null=True)),
                ('Department', models.TextField(default='', null=True)),
                ('Role', models.TextField(default='', null=True)),
                ('Competency', models.TextField(default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='persoinfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=200, null=True)),
                ('Contactno', models.CharField(default='', max_length=200, null=True)),
                ('Email', models.CharField(default='', max_length=200, null=True)),
                ('DateofBirth', models.CharField(default='', max_length=200, null=True)),
                ('Gender', models.CharField(default='', max_length=200, null=True)),
                ('Department', models.TextField(default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='projectabout',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Projectname', models.CharField(default='', max_length=2000, null=True)),
                ('Painpoints', models.TextField(default='', null=True)),
                ('Solution', models.TextField(default='', null=True)),
                ('Innovation', models.TextField(default='', null=True)),
                ('Features', models.TextField(default='', null=True)),
                ('Customers', models.TextField(default='', null=True)),
                ('Availability', models.TextField(default='', null=True)),
                ('Businessmodel', models.TextField(default='', null=True)),
                ('Projectname_reconfirmation', models.CharField(default='', max_length=2000, null=True)),
                ('Specifications', models.CharField(default='', max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='teamdeta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Teamdetails', models.CharField(default='', max_length=2000, null=True)),
            ],
        ),
    ]
