# Generated by Django 4.2.3 on 2023-07-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='documentuploadss',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SL', models.IntegerField(null=True)),
                ('files', models.FileField(default='', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='memberdets',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_id', models.IntegerField(null=True)),
                ('MemberName', models.CharField(default='', max_length=200, null=True)),
                ('Contactnumber', models.CharField(default='', max_length=200, null=True)),
                ('Email', models.CharField(default='', max_length=200, null=True)),
                ('DateofBirth', models.CharField(default='', max_length=200, null=True)),
                ('Gender', models.CharField(default='', max_length=200, null=True)),
                ('Department', models.TextField(default='', null=True)),
                ('Role', models.TextField(default='', null=True)),
                ('Competency', models.TextField(default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='newuserdets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SL', models.IntegerField(null=True)),
                ('firstname', models.CharField(default='', max_length=200, null=True)),
                ('lastname', models.CharField(default='', max_length=200, null=True)),
                ('username', models.CharField(default='', max_length=200, null=True)),
                ('emailaddress', models.CharField(default='', max_length=200, null=True)),
                ('password', models.TextField(default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='persoinfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SL', models.IntegerField(null=True)),
                ('Name', models.CharField(default='', max_length=200, null=True)),
                ('Contactno', models.CharField(default='', max_length=200, null=True)),
                ('Email', models.CharField(default='', max_length=200, null=True)),
                ('DateofBirth', models.CharField(default='', max_length=200, null=True)),
                ('Gender', models.CharField(default='', max_length=200, null=True)),
                ('Department', models.TextField(default='', null=True)),
                ('Projectname', models.CharField(default='', max_length=2000, null=True)),
                ('Painpoints', models.TextField(default='', null=True)),
                ('Solution', models.TextField(default='', null=True)),
                ('Innovation', models.TextField(default='', null=True)),
                ('Features', models.TextField(default='', null=True)),
                ('Customers', models.TextField(default='', null=True)),
                ('Availability', models.TextField(default='', null=True)),
                ('Businessmodel', models.TextField(default='', null=True)),
                ('Projectdomain', models.CharField(default='', max_length=2000, null=True)),
                ('Specifications', models.CharField(default='', max_length=2000, null=True)),
                ('Teamdetails', models.CharField(default='', max_length=2000, null=True)),
            ],
        ),
    ]
