# Generated by Django 4.1 on 2023-07-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdets',
            name='total_members',
            field=models.IntegerField(default=0),
        ),
    ]
