# Generated by Django 4.1 on 2023-07-04 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_memberdets_total_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberdets',
            name='total_members',
        ),
    ]
