# Generated by Django 4.1 on 2023-07-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_remove_memberdets_total_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdets',
            name='Membernumber',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
