# Generated by Django 4.1 on 2023-07-05 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_memberdets_membernumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectabout',
            old_name='Projectname_reconfirmation',
            new_name='Projectdomain',
        ),
    ]
