# Generated by Django 4.1 on 2023-07-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_rename_projectname_reconfirmation_projectabout_projectdomain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberdets',
            name='Membernumber',
        ),
        migrations.AddField(
            model_name='memberdets',
            name='project_id',
            field=models.IntegerField(null=True),
        ),
    ]
