# Generated by Django 4.1 on 2023-07-06 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_remove_memberdets_membernumber_memberdets_project_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberdets',
            old_name='id',
            new_name='member_id',
        ),
    ]
