# Generated by Django 4.1 on 2023-07-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_rename_id_memberdets_member_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='projectabout',
        ),
        migrations.DeleteModel(
            name='teamdeta',
        ),
        migrations.AddField(
            model_name='persoinfo',
            name='Availability',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='persoinfo',
            name='Businessmodel',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='persoinfo',
            name='Customers',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='persoinfo',
            name='Features',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='persoinfo',
            name='Innovation',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='persoinfo',
            name='Painpoints',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='persoinfo',
            name='Projectdomain',
            field=models.CharField(default='', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='persoinfo',
            name='Projectname',
            field=models.CharField(default='', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='persoinfo',
            name='SL',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='persoinfo',
            name='Solution',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='persoinfo',
            name='Specifications',
            field=models.CharField(default='', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='persoinfo',
            name='Teamdetails',
            field=models.CharField(default='', max_length=2000, null=True),
        ),
    ]
