# Generated by Django 4.1 on 2023-07-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_delete_projectabout_delete_teamdeta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='newuserdets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SL', models.IntegerField(null=True)),
                ('firstname', models.CharField(default='', max_length=200, null=True)),
                ('lastname', models.CharField(default='', max_length=200, null=True)),
                ('username', models.CharField(default='', max_length=200, null=True)),
                ('emailaddress', models.CharField(default='', max_length=200, null=True)),
                ('password', models.TextField(default='', null=True)),
            ],
        ),
    ]
