# Generated by Django 4.1 on 2023-07-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_newuserdets'),
    ]

    operations = [
        migrations.CreateModel(
            name='documentupload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SL', models.IntegerField(null=True)),
                ('files', models.FileField(default='', null=True, upload_to='')),
            ],
        ),
    ]
